name: NLP Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Run Python syntax check
        run: |
          python -m py_compile *.py

      - name: Run main script (optional)
        run: |
          python main.py

      # Uncomment the following if you have test scripts
      # - name: Run tests
      #   run: |
      #     pytest
