name: NLP Project CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Run Python syntax check
        run: python -m py_compile *.py 

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd NLP-proj1
            git pull origin main
            pip install -r requirements.txt
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
            pkill -f web.py || true
            nohup python3 web.py > log.txt 2>&1 &
