google_cloud:
  project_id: your-project-id
  credentials_path: path/to/your/credentials.json
  api_endpoint: language.googleapis.com
  region: us-central1

  natural_language_api:
    enabled: true
    features:
      - sentiment_analysis
      - entity_analysis
      - syntax_analysis

  automl_natural_language:
    enabled: true
    model_id: your-automl-model-id
    location: us-central1
    score_threshold: 0.5

  gcs:
    enabled: true
    bucket_name: your-gcs-bucket-name
    dataset_path: datasets/
    model_path: models/
    output_path: output/

env:
  GOOGLE_APPLICATION_CREDENTIALS: path/to/your/credentials.json
  GOOGLE_CLOUD_PROJECT: your-project-id
